version: '3.8'
services:
  backend_vinculation:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - ./ssl:/app/ssl
    environment:
      NODE_ENV: development
      NODE_EXTRA_CA_CERTS: /app/ssl/DigiCertGlobalRootG2.crt.pem
    depends_on:
      - db
    command: sh -c "npm install && npm run start:dev"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
